### ISSUE TITLE
Chrome Add-on doesn't always work

### ISSUE THREAD

**Issue by jkwasnik** [narcan/api-tools#3]
Hi, I've installed the GA Management Magic add-on to my Chrome browser, which is the most up to date version. However, sometimes I only get the Help menu instead of all of the options when I click on Add-ons --> GA Management Magic on Google Sheets. Can you tell me what I might be doing wrong?

**Comment by narcan** [comment]
I've seen that symptom myself. I assumed it was other adds that I had, or the fact that I develop other add-ons that might be causing conflicts. Uninstalling and reinstalling has done it for me, but I'm not sure of the root cause.

**Comment by pschneider87** [comment]
I get a error for updating custom Dimensions:

Message details
Script function not found: requestDimensionUpdate For more information, see https://developers.google.com/apps-script/reference/base/menu#addItem(String,String)

Any Idea to solve this?

**Comment by boyislaw** [comment]
I have same error when trying to update Custom Dimensions:

Script function not found: requestDimensionUpdate For more information, see https://developers.google.com/apps-script/reference/base/menu#addItem(String,String)

**Comment by narcan** [comment]
requestDimensionUpdate issue has been fixed

**Comment by boyislaw** [comment]
Do we need to update add-on?

**Comment by pschneider87** [comment]
Unfortunately, I still get the error:

Script function not found: requestDimensionUpdate For more information, see https://developers.google.com/apps-script/reference/base/menu#addItem(String,String)

What's to do?
Thanks!

**Comment by pschneider87** [comment]
any update?

**Comment by mannbarry2** [comment]
Script function not found: requestDimensionUpdate 

Any update?

**Comment by narcan** [comment]
###Update
**The requestDimensionUpdate issue has been fixed** in the latest release, which also adds metric and filter list/update functionality similar to the existing dimension list/update functionality.

I've also added the ability to **format currently active sheets for metrics, filters and dimensions**. Hope it's to your liking!
